---
- name: install maven
  get_url: url=http://archive.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz dest={{ maven_temporary_location }}

- name: unzip maven
  unarchive: src={{ maven_temporary_location }} dest=/var/lib copy=no

- name: create symbolic link
  shell: rm -rf {{ maven_symlink_location }} && ln -s /var/lib/apache-maven-{{ maven_version }}/bin/mvn {{ maven_symlink_location }}
