server:
  port: 0

#
# >> If you are using spring-cloud-starter-consul-all or spring-cloud-starter-consul-config, you need to put values in bootstrap.properties.
#
# https://github.com/spring-cloud/spring-cloud-consul/blob/master/docs/src/main/asciidoc/spring-cloud-consul.adoc#registering-with-consul
#
#spring:
#  cloud:
#    consul:
#      host: localhost
#      port: 8500

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG
    org.apache.http: DEBUG