spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        preferIpAddress: false
        ipAddress: 127.0.0.1

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG